### PR TITLE
Before purchase blocks are executed multiple time for same tick

### LINKED ISSUE #518: a BUG on "WATCH & PURCHASE CONTRACT" BLOCK (FOREX) --- BUG
@aminmarashi @gokula-krishna-dev we need some bug repellents or insecticides here!! lol.

to day i tried some forex strategy to binary bot.
i felt something wrong as the bot didn't worked as it should, so checked it out and found this BUG.
**the bot execute the script on "WATCH & PURCHASE CONTRACT" block twice (or even trice) on very tick.**
but when i changed the asset to volatility idx, everything works fine. this BUG only happen on forex (i only checked forex and volatility, so idk about the other assets).

here is the test i made to check the bug.
[TES-BLOCK(2)-EXECUTED.zip](https://github.com/binary-com/binary-bot/files/1709700/TES-BLOCK.2.-EXECUTED.zip)
error_on_purchase_block**

### PR DESCRIPTION
**Pull request by gokula-krishna-dev**
| Q                        | A 
| ------------------------ | ---
| Fixed Issues?            | Fixes #518
| Patch: Bug Fix?          |
| Major: Breaking Change?  |
| Minor: New Feature?      |
| Tests Added + Pass?      | Yes
| Does not reduce coverage?| Yes
| Any Dependency Changes?  |

### CODE REVIEW

File: src/botPage/bot/TradeEngine/index.js [hunk 1]
```diff
@@ -17,18 +17,30 @@ import rootReducer from './state/reducers';
...
+        },
     });
 
 const watchDuring = store =>
-    watchScope({ store, stopScope: constants.STOP, passScope: constants.DURING_PURCHASE, passFlag: 'openContract' });
+    watchScope({
+        store,
+        stopScope    : constants.STOP,
+        passScope    : constants.DURING_PURCHASE,
+        passCondition: state => state.openContract,
```
Comment (aminmarashi) [inline src/botPage/bot/TradeEngine/index.js]: It seems like the problem can still happen in here. As both `proposal_open_contract` and `ticks` can trigger the condition.

A more general purpose solution would be to move the `lastTick` check to the `watchScope` function.

For simplicity `watchScope` can return a closure containing the `lastTick` variable.

```
const watchScope = ({ store, stopScope, passScope, passCondition }) => {
  ...
  let lastTick;
  return new Promise(resolve => {
    const unsubscribe = store.subscribe(() => {
      if (newState.newTick === lastTick) return;
      lastTick = newState.newTick;

      ... // The rest can be the same as before, as we don't check the ticks anymore we can used the flag instead of the condition
        
}
```

Comment (gokula-krishna-dev) [reply src/botPage/bot/TradeEngine/index.js]: Done

Comment (aminmarashi) [reply src/botPage/bot/TradeEngine/index.js]: I don't think we need `passCondition` anymore, better to move it back to `passFlag`.

File: src/botPage/bot/TradeEngine/index.js [hunk 2]
```diff
@@ -20,15 +20,26 @@ import { start } from './state/actions';
...
+    });
 
-const watchScope = ({ store, stopScope, passScope, passFlag }) => {
+let prevTick;
+const watchScope = ({ store, stopScope, passScope, passCondition }) => {
```
Comment (aminmarashi) [inline src/botPage/bot/TradeEngine/index.js]: It's better to move `prevTick` to inside `watchScope`, otherwise, it's polluting the module scope and the `prevTick` from one scope might interfere with other non-related scope (user can miss one tick for `before` scope)
